name: Deploy Competence

on:
  push:
    branches:
      - main
      - abdellah

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy application
        run: |
          cd /var/www/html/Competence

          echo "Fetching latest changes..."
          git fetch origin

          echo "Deploying branch: $GITHUB_REF_NAME"
          git checkout -B "$GITHUB_REF_NAME" "origin/$GITHUB_REF_NAME"

          echo "Deployment completed successfully."
